### ISSUE TITLE
Error: Cannot find module 'gulp-sass'

### ISSUE THREAD

**Issue by kumarryogeshh** [BlackrockDigital/startbootstrap-sb-admin#48]
```
startbootstrap-sb-admin (master)$ gulp dev
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/startbootstrap-sb-admin/gulpfile.js:2:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by f3ltron** [comment]
install it manually or add it to package.json

npm install -g gulp-sass or npm install --save gulp-sass

**Comment by davidtmiller** [comment]
This should be fixed now with the build.
